[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run railway:build"]

[start]
cmd = "npm run start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
